name: Stillstate Wellness
favicon: null
layout_spectrum: 0.46922
typography_spectrum: 0.56876
title: Stillstate Wellness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5dc8c0'
    - '#7cedcf'
    - '#2a7463'
    - '#beeee4'
    - '#4ca49e'
  brandStrength: 0.34140698867850006
  lightness: 0.6671203398145735
  saturation: 0.2740284714382142
  rhythmicContrast: 0.30474933283403516
purpose: []
